version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.site
    image: andrewkozyar1/lab4_devops:compose-django
    container_name: django
    networks:
      - publ
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    image: andrewkozyar1/lab4_devops:compose-monitoring
    container_name: monitoring
    depends_on:
      - django
    network_mode: host
    volumes:
      - monit-log:/app/

volumes:
  monit-log:
    driver: local

networks:
  publ:
    driver: bridge
  Â© 2019 GitHub, Inc.